insert into medicine_major (medicine_major_category_id, name, eng_name, abbreviation)
values (1, '미생물학교실', 'Microbiology', 'none'),
       (1, '병리학교실', 'Pathology', 'PA'),
       (1, '생리학교실', 'Physiology', 'none'),
       (1, '생화학분자생물학교실', 'Biochemistry and Molecular Biology', 'none'),
       (1, '약리학교실', 'Pharmacology', 'none'),
       (1, '예방의학교실', 'Preventive Medicine and Public Health', 'none'),
       (1, '의생명과학부', 'Biomedical Science Institute', 'none'),
       (1, '의생명시스템정보학교실', 'Biomedical Systems Informatics', 'none'),
       (1, '의학공학교실', 'Medical Engineering', 'none'),
       (1, '해부학교실', 'Anatomy', 'none'),
       (1, '환경의생물학교실', 'Environmental Medical Biology', 'none'),
       (2, '감염내과', 'Infection Medicine ', 'M7'),
       (2, '내분비내과', 'Endocrinology', 'M5'),
       (2, '노년내과', 'Geriatrics', 'MG'),
       (2, '류마티스내과', 'Rheumatology', 'M9'),
       (2, '소화기내과', 'Gastroenterology', 'M1'),
       (2, '신장내과', 'Nephrology', 'M8'),
       (2, '심장내과', 'Cardiology', 'M3'),
       (2, '알레르기내과', 'Allergy Medicine ', 'M6'),
       (2, '종양내과', 'Oncology', 'CA'),
       (2, '통합내과', 'Integrated Medicine', 'MU'),
       (2, '혈액내과', 'Hematology', 'M2'),
       (2, '호흡기내과', 'Pulmonary Medicine ', 'CM'),
       (2, '간담췌외과', 'Hepatobiliary and Pancreatic Surgery ', 'G6'),
       (2, '갑상선내분비외과', 'Thyroid & Endocrine Surgery ', 'G8'),
       (2, '대장항문외과', 'Colorectal Surgery', 'G5'),
       (2, '소아외과', 'Pediatric Surgery', 'G2'),
       (2, '위장관외과', 'Gastrointestinal Surgery', 'G4'),
       (2, '유방외과', 'Breast Surgery', 'G7'),
       (2, '이식외과', 'Transplantation Surgery', 'G3'),
       (2, '중환자외상외과', 'none', 'none'),
       (2, '소아감염면역과', 'Pediatric Infection and Immunity ', 'PI'),
       (2, '소아과학교실', 'Pediatrics', 'PD'),
       (2, '소아내분비과', 'Pediatric Endocrinology ', 'PE'),
       (2, '소아마취통증의학과', 'Pediatric Anesthesiology', 'A4'),
       (2, '소아비뇨의학과', 'Pediatric Urology', 'P6'),
       (2, '소아소화기영양과', 'Pediatric Gastroenterology ', 'PG'),
       (2, '소아신경과', 'Division of Pediatric Neurology ', 'P8'),
       (2, '소아신경외과', 'Department of Pediatric Neurosurgery ', 'P4'),
       (2, '소아신장과', 'Pediatric Nephrology ', 'PN'),
       (2, '소아심장과', 'Pediatric Cardiology ', 'P2'),
       (2, '소아응급의학과', 'Pediatric Emergency Medicine ', 'PP'),
       (2, '소아재활의학과', 'none', 'P9'),
       (2, '소아정신과', 'Department of Pediatric Psychiatry ', 'P3'),
       (2, '소아정형외과', 'Department of Pediatric Orthopedic Surgery ', 'P5'),
       (2, '소아청소년과', 'Pediatrics ', 'P1'),
       (2, '소아청소년부인과', 'Pediatric Gynaecology', 'PB'),
       (2, '소아혈액종양과', 'Pediatric Oncology ', 'PO'),
       (2, '소아호흡기 알레르기과', 'Pediatric Pulmonology and Allergy ', 'PR'),
       (2, '신생아과', 'Division of Neonatology ', 'P7'),
       (2, '심장마취통증의학과', 'Cardiac Anesthesiology', 'A2'),
       (2, '가정의학과', 'Family Medicine', 'HM'),
       (2, '마취통증의학과', 'Anesthesiology ', 'AN'),
       (2, '방사선종양학과', 'Radiation Oncology', 'TR'),
       (2, '비뇨의학과', 'Urology', 'UR'),
       (2, '산부인과', 'Obstetrics and Gynecology', 'OB'),
       (2, '성형외과', 'Plastic Surgery ', 'PS'),
       (2, '신경과', 'Neurology', 'NM'),
       (2, '신경외과', 'Neurosurgery', 'NS'),
       (2, '안과', 'Ophthalmology', 'EY'),
       (2, '영상의학과', 'Radiology', 'RD'),
       (2, '응급의학과', 'Emergency', 'EM'),
       (2, '이비인후과', 'Otorhinolaryngology', 'EN'),
       (2, '재활의학과', 'Rehabilitation Medicine', 'RH'),
       (2, '정신건강의학과', 'Psychiatry', 'PY'),
       (2, '정형외과', 'Orthopaedic Surgery', 'OS'),
       (2, '진단검사의학과', 'Laboratory Medicine', 'LB'),
       (2, '피부과', 'Dermatology', 'SK'),
       (2, '핵의학과', 'Nuclear Medicine', 'NU'),
       (2, '흉부외과', 'Chest Surgery', 'C1'),
       (2, '암예방과', 'none', 'CV'),
       (2, '임상유전과', 'Clinical Genetics ', 'CG'),
       (2, '입원전담의학과', 'Hospital Medicine', 'HP'),
       (2, '종양마취통증의학과', 'Department of Oncologic Anesthesiology ', 'A3'),
       (2, '종양정신건강의학과', 'Department of Psychiatric Oncology ', 'PC'),
       (2, '임상약리학과', 'Clinical Pharmacology ', 'CP'),
       (3, '법의학과', 'Forensic Medicine', 'none'),
       (3, '의료법윤리학과', 'Medical Law and Ethics', 'none'),
       (3, '의사학과', 'Medical History', 'none'),
       (3, '의학교육학교실', 'Medical Education', 'none'),
       (3, '통일/국제의료영역', 'Global Healthcare Korean Unification', 'none');